buildx with debug log

diff --git a/.github/workflows/ci_pipeline.yml b/.github/workflows/ci_pipeline.yml
--- a/.github/workflows/ci_pipeline.yml
+++ b/.github/workflows/ci_pipeline.yml
@@ -62,7 +62,9 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-        continue-on-error: true
+        with:
+          buildkitd-flags: --debug
+#        continue-on-error: true
 
       - name: Log in to Harbor
         uses: docker/login-action@v3
@@ -70,13 +72,13 @@ jobs:
           registry: ${{ secrets.HARBOR_URL }}
           username: ${{ secrets.HARBOR_USERNAME }}
           password: ${{ secrets.HARBOR_PASSWORD }}
-        continue-on-error: true
-
-      - name: Check daemon logs
-        run: |
-          journalctl -u docker.service
-          echo "Throw error to fail the build"
-          exit 1
+#        continue-on-error: true
+#
+#      - name: Check daemon logs
+#        run: |
+#          journalctl -u docker.service
+#          echo "Throw error to fail the build"
+#          exit 1
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
