Check docker daemon logs

diff --git a/.github/workflows/ci_pipeline.yml b/.github/workflows/ci_pipeline.yml
--- a/.github/workflows/ci_pipeline.yml
+++ b/.github/workflows/ci_pipeline.yml
@@ -61,6 +61,7 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
+        continue-on-error: true
 
       - name: Log in to Harbor
         uses: docker/login-action@v3
@@ -68,6 +69,13 @@ jobs:
           registry: ${{ secrets.HARBOR_URL }}
           username: ${{ secrets.HARBOR_USERNAME }}
           password: ${{ secrets.HARBOR_PASSWORD }}
+        continue-on-error: true
+
+      - name: Check daemon logs
+        run: |
+          journalctl -u docker.service
+          echo "Throw error to fail the build"
+          exit 1
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
